name: checks

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # ensures proper formatting and clippy lint
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-07-23
          components: rustfmt, clippy

      - name: Run Linters
        run: make lint

  # ensures build is successful
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-07-23

      - name: Build Code
        run: make rust-build

      - name: Create artifact
        run: |
          cd ./target/release
          tar -czf era_revm-${{ matrix.os }}.tar.gz ./era_revm*

      - name:  Upload artifact
        uses:  actions/upload-artifact@v3
        with:
          name: era_revm-${{ matrix.os }}.tar.gz
          path: ./target/release/era_revm-${{ matrix.os }}.tar.gz